spring:
  datasource:
       type: com.alibaba.druid.pool.DruidDataSource
       url: jdbc:sqlserver://127.0.0.1:1434;DatabaseName=research-supervision
       username: sa
       password: sherlock
logging:
  level:
    org.hswebframework.web: DEBUG
    org.hswebframework.web.cache: WARN
    org.hswebframework.iot: DEBUG
    org.apache.ibatis: DEBUG
    org.mybatis: DEBUG
