server:
    port: 8056
spring:
  aop:
      auto: true
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      max-active: 1000
      initial-size: 5
      min-idle: 5
      max-wait: 50000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      validation-query: select 1
      time-between-eviction-runs-millis: 60000
      max-open-prepared-statements: 2000
  application:
    name: carmes
  profiles:
    active: dev
fastjson:
  features : WriteDateUseDateFormat
hsweb:
    app:
      name: carmes
      version: 1.0.0
    authorize:
#      auto-parse: true
#      sync: true
      allopatric-login-modes:
          iot-cloud-user: offlineOther #异地登录模式,踢出其他地方登录的用户
    socket:
      max-text-message-buffer-size: 10485760
    users:
      gateway-user:
        username: ceprei-gateway
        password: admin
eureka:
  client:
    service-url:
      defaultZone: http://${eureka-host:localhost}:${eureka-port:8761}/eureka/
  instance:
    appname: ${spring.application.name}

logging:
  level:
    system: TRACE
    business: TRACE

mybatis:
  mapper-locations: classpath*:com/ceprei/**/*Mapper.xml
  type-handlers-package: com.ceprei.common.api.enums
